name: Career Services Application CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up python environment
      - name: Set up Python Environment
        uses: actions/setup-python@v2

      # Intall backend dependencies/libraries
      - name: Intall backend dependencies/libraries
        run: |
          python -m pip install --upgrade pip
          pip install flask==2.0.3 flask-bcrypt==1.0.1 flask-sqlalchemy==2.5.1 flask-restful==0.3.9 pytest==7.1.2 werkzeug==2.0.3
          pip install --upgrade sqlalchemy

      # Run backend apis' unit tests
      - name: Run Backend Unit Tests
        working-directory: Sprint 3/code/tests
        run: |
          pytest test_app_units.py
