name: Career Services Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    runs-on: windows-latest

    # Checkout code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up python environment
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Install backend dependencies/libraries and use database file
      - name: Install backend dependencies/libraries
        run: |
          python -m pip install --upgrade pip
          pip install flask==2.2.5 flask-bcrypt==1.0.1 flask-restful==0.3.10 flask-sqlalchemy==3.0.5 pytest==7.1.2 pytest-flask==1.2.0 werkzeug==2.2.2 flask-socketio==5.3.5

      # Run backend apis' tests
      - name: Run Backend Tests
        working-directory: Sprint 4/code/tests/
        run: |
          pytest -vv test_app_units.py
