name: Career Services Application CI

on:
  push:
    branches:
      - Testing-Contiuous-Integration
  workflow_dispatch: # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up python environment
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Intall backend dependencies/libraries and use database file
      - name: Intall backend dependencies/libraries
        run: |
          python -m pip install --upgrade pip
          pip install flask==2.2.5 flask-bcrypt==1.0.1 flask-restful==0.3.10 flask-sqlalchemy==3.0.5 pytest==7.1.2 werkzeug==2.2.2
          python Sprint 3/code/db.py
          
      # Run backend apis' unit tests
      - name: Run Backend Unit Tests
        working-directory: Sprint 3/code/tests
        run: |
          pytest test_app_units.py
