name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:   # Manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Frontend build and test
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: npm install --prefix sprint3/code/tests

      - name: Run frontend tests
        run: npm test --prefix sprint3/code/tests

      # Backend build and test
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install backend dependencies
        run: pip install -r sprint3/code/requirements.txt

      - name: Install Flask
        run: pip install Flask

      - name: Run backend tests
        run: pytest sprint3/code/tests
